### ISSUE TITLE
Resize columns

### ISSUE THREAD

**Issue by hoverdave** [JonathanFeenstra/modorganizer-loot-warning-checker#1]
Hello, thank you for the very handy plugin! A suggestion and request, can you make the modname/text columns resizeable so we can potentially read the entire message on each?

**Comment by JonathanFeenstra** [comment]
Thank you for the suggestion, but unfortunately this is not possible through a plugin. I already posted this as a suggestion in MO2's Discord server, maybe an issue should be opened on their [main repository](https://github.com/ModOrganizer2/modorganizer/issues) as well.

**Comment by JonathanFeenstra** [comment]
I opened a [PR](https://github.com/ModOrganizer2/modorganizer/pull/2128) on the MO2 repository to make the columns automatically resize to their contents. I considered making them manually resizable, but due to constraints in the UI framework, that would require the column headers to be made visible. The PR has been merged, so it should be resolved in version 2.5.3 of Mod Organizer once it's released.
